DROP TABLE IF EXISTS adoptions;
DROP TABLE IF EXISTS animals;
DROP TABLE IF EXISTS staff;
DROP TABLE IF EXISTS species;

CREATE TABLE species (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE staff (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    role TEXT NOT NULL
    -- You may omit this check if using older SQLite versions
    -- CHECK (role IN ('adoption', 'veterinarian', 'caretaker'))
);

CREATE TABLE animals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    species_id INTEGER NOT NULL,
    age INTEGER NOT NULL CHECK (age >= 0),
    arrived_on DATE NOT NULL,
    adopted BOOLEAN DEFAULT 0,
    FOREIGN KEY (species_id) REFERENCES species(id)
);

CREATE TABLE adoptions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    animal_id INTEGER NOT NULL,
    adopted_by TEXT NOT NULL,
    adopted_on DATE NOT NULL,
    staff_id INTEGER,
    FOREIGN KEY (animal_id) REFERENCES animals(id),
    FOREIGN KEY (staff_id) REFERENCES staff(id)
);

-- Sample data
INSERT INTO species (name) VALUES ('Dog');
INSERT INTO species (name) VALUES ('Cat');
INSERT INTO species (name) VALUES ('Rabbit');
INSERT INTO species (name) VALUES ('Parrot');

INSERT INTO staff (name, role) VALUES ('Alice', 'adoption');
INSERT INTO staff (name, role) VALUES ('Bob', 'veterinarian');
INSERT INTO staff (name, role) VALUES ('Carol', 'caretaker');
INSERT INTO staff (name, role) VALUES ('Dave', 'adoption');
INSERT INTO staff (name, role) VALUES ('Eve', 'caretaker');

INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 2, 4, '2025-01-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 4, '2025-04-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 3, 1, '2025-04-14', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 3, '2024-12-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 2, 3, '2024-11-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 1, 8, '2025-01-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 4, 7, '2025-05-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 6, '2025-06-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 2, 5, '2025-01-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 3, 9, '2024-12-30', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 1, 10, '2025-03-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 3, 5, '2025-05-29', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 4, 3, '2024-12-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 4, 8, '2025-05-23', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 3, 2, '2025-06-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 1, 4, '2024-12-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 2, 10, '2025-06-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 3, 2, '2025-04-22', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 4, 7, '2025-02-24', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 1, 5, '2025-05-20', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 4, 12, '2024-12-11', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 3, 1, '2025-03-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 3, 9, '2025-05-21', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 2, 10, '2025-03-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 2, 10, '2024-11-09', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 2, 10, '2024-11-15', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 3, 8, '2025-06-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 2, 11, '2025-05-11', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 1, 8, '2024-12-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 4, 2, '2025-01-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 4, 8, '2025-03-24', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 2, 6, '2025-02-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 4, 12, '2025-04-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 2, 1, '2025-06-05', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 1, 10, '2025-04-19', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 1, '2025-04-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 4, 5, '2024-11-14', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 1, 12, '2025-06-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 2, 7, '2025-04-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 2, 8, '2025-03-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 5, '2025-01-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 1, 6, '2025-02-24', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 1, 10, '2025-01-22', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 3, 8, '2025-06-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 3, 3, '2025-06-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 2, 8, '2024-11-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 3, 11, '2025-05-31', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 4, 6, '2025-04-03', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 2, 10, '2025-05-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 4, 5, '2025-03-22', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 4, 5, '2025-02-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 1, 10, '2025-01-17', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 2, 9, '2025-01-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 3, 6, '2025-01-31', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 3, 6, '2025-01-15', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 3, 2, '2025-04-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 2, 1, '2024-12-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 3, '2024-11-18', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 4, 2, '2025-05-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 4, 9, '2024-11-13', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 3, 12, '2025-02-12', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 1, 2, '2024-12-16', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 3, 3, '2025-02-27', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 10, '2025-02-27', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 8, '2025-05-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 3, 4, '2025-02-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 1, 2, '2025-01-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 1, 3, '2024-11-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 4, 1, '2025-05-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 4, 4, '2025-06-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 3, '2025-03-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 1, 1, '2024-11-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 3, 4, '2024-12-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 2, 9, '2024-11-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 1, 4, '2024-12-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 1, 9, '2024-12-13', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 4, 7, '2025-04-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 3, 12, '2025-05-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 1, 11, '2025-01-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 4, 11, '2025-01-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 3, 3, '2025-04-20', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 3, 3, '2025-02-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 3, 9, '2025-03-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 1, 8, '2025-03-19', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 4, '2025-05-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 3, 4, '2025-05-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 12, '2024-12-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 3, 10, '2025-04-20', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 3, 3, '2025-04-23', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 3, 11, '2024-11-30', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 1, 2, '2025-02-26', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 2, 6, '2025-02-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 2, 4, '2024-12-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 4, 9, '2025-04-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 3, 8, '2024-12-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 2, 8, '2025-02-16', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 2, 5, '2025-01-17', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 1, 3, '2024-11-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 1, 2, '2025-04-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 4, 3, '2025-03-26', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 1, 12, '2024-12-23', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 3, 6, '2025-02-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 2, 1, '2025-03-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 2, '2024-12-26', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 2, 11, '2025-04-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 4, 3, '2025-02-15', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 3, 5, '2025-06-11', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 3, 8, '2025-03-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 2, 4, '2025-01-02', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 1, 9, '2024-11-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 1, 5, '2025-04-18', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 3, 8, '2025-05-20', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 11, '2025-03-14', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 3, 3, '2025-04-27', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 4, 2, '2025-01-18', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 1, 3, '2025-06-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 2, 7, '2025-01-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 4, 2, '2025-04-24', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 4, 3, '2024-12-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 1, 7, '2025-04-20', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 3, 10, '2025-06-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 7, '2025-02-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 2, 9, '2025-01-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 1, 12, '2025-05-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 2, 2, '2025-02-14', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 1, 9, '2024-11-30', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 9, '2025-01-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 4, 6, '2025-01-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 2, 4, '2025-01-24', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 7, '2025-03-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 2, 12, '2025-03-14', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 2, '2025-01-30', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 4, 9, '2024-11-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 1, 4, '2025-05-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 1, 10, '2025-02-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 2, 4, '2024-11-16', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 2, 3, '2025-01-10', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 2, '2025-02-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 1, 1, '2025-04-23', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 4, 1, '2025-04-26', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 12, '2025-01-28', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 3, 11, '2025-01-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 3, 12, '2025-06-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 4, 12, '2025-02-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 4, 12, '2025-01-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 7, '2025-05-23', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 2, 4, '2025-01-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 4, 10, '2024-11-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 3, 10, '2024-12-19', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 3, 2, '2025-01-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 1, 1, '2025-06-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 4, 6, '2025-02-05', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 11, '2025-02-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 7, '2025-06-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 4, 4, '2024-12-11', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 3, 11, '2025-01-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 2, 7, '2025-01-31', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 2, 7, '2025-03-18', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 2, 8, '2024-11-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 4, 12, '2024-12-26', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 3, 11, '2024-11-16', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 2, '2025-01-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 5, '2025-01-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 3, 7, '2025-05-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 9, '2024-11-24', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 10, '2025-03-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 7, '2025-02-15', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 4, 12, '2025-02-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 2, 3, '2025-05-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 2, 4, '2025-01-23', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 4, '2025-03-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 4, '2025-06-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 2, '2025-04-09', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 2, 10, '2025-04-17', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 3, '2025-01-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 11, '2025-05-03', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 5, '2025-03-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 1, 12, '2024-11-23', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 3, 2, '2025-05-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 4, 3, '2025-02-20', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 3, 1, '2024-11-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 10, '2024-12-10', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 3, 4, '2025-03-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 3, '2025-05-19', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 4, 9, '2025-06-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 1, 7, '2025-04-21', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 3, 7, '2025-05-03', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 2, 6, '2025-02-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 6, '2024-12-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 1, 3, '2025-03-24', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 1, 8, '2024-12-12', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 4, 6, '2024-12-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 5, '2025-01-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 1, 11, '2025-05-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 3, 12, '2024-11-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 2, 8, '2024-12-30', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 2, 11, '2024-12-09', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 2, 6, '2025-01-18', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 2, 11, '2024-11-14', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 2, 6, '2024-11-29', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 2, 1, '2025-01-18', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 4, 6, '2025-06-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 9, '2025-01-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 1, 12, '2024-12-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 4, 2, '2025-01-09', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 3, 6, '2025-02-22', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 2, '2025-03-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 3, 4, '2025-04-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 4, 12, '2025-03-28', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 2, 1, '2025-01-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 2, 8, '2025-04-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 3, 12, '2025-01-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 4, 4, '2025-05-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 2, 10, '2024-12-17', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 2, 1, '2024-12-29', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 1, 7, '2025-05-23', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 8, '2025-02-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 3, '2025-03-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 2, 11, '2025-05-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 3, 10, '2025-06-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 4, 7, '2025-02-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 2, 2, '2025-01-04', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 1, 6, '2025-06-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 3, 8, '2025-03-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 1, 2, '2025-04-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 2, 6, '2025-04-27', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 2, 6, '2025-05-19', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 5, '2024-11-06', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 10, '2025-03-02', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 4, 12, '2024-12-02', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 1, 10, '2025-01-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 1, 3, '2024-12-29', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 5, '2025-01-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 2, 10, '2025-05-20', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 1, 5, '2025-03-18', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Chloe', 1, 7, '2024-12-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 6, '2025-02-05', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 6, '2025-04-24', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Shadow', 4, 6, '2025-06-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 2, 6, '2025-04-29', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 3, 2, '2025-01-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 1, 5, '2024-12-13', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 1, 10, '2025-04-22', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 1, 3, '2025-04-03', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 5, '2025-04-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 2, 5, '2025-02-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 4, 10, '2025-02-20', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 3, 2, '2024-11-04', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 2, 9, '2025-02-15', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 3, 4, '2024-12-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 3, 3, '2025-03-18', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 8, '2025-01-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 1, 7, '2025-04-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 2, 5, '2024-12-22', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 3, 3, '2025-05-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 1, 3, '2025-01-28', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 3, 8, '2025-06-03', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 4, 9, '2024-12-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 1, 3, '2024-12-16', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 1, 1, '2024-11-05', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 1, 4, '2024-11-01', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 4, 5, '2025-05-13', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 6, '2024-11-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Pepper', 3, 5, '2025-05-08', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 4, 7, '2024-11-13', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 4, 2, '2025-02-07', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Bella', 2, 11, '2025-03-03', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buster', 2, 12, '2025-01-11', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 2, 4, '2025-02-25', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 4, 9, '2025-01-21', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 2, 8, '2024-12-07', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Coco', 2, 10, '2025-05-24', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 1, 2, '2025-04-29', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 4, 2, '2025-05-22', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 4, 3, '2025-01-08', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Max', 1, 12, '2025-02-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 1, 5, '2025-05-04', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 3, 4, '2025-05-22', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Charlie', 2, 8, '2025-06-09', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 3, 9, '2025-04-18', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Buddy', 3, 3, '2025-01-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 3, 4, '2025-03-02', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 10, '2024-11-03', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Milo', 2, 8, '2025-04-27', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Luna', 3, 11, '2025-03-12', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 2, 6, '2024-12-06', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 4, 11, '2025-02-21', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Daisy', 2, 4, '2025-05-03', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Sasha', 2, 9, '2024-11-24', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ruby', 2, 10, '2025-04-11', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Jack', 4, 12, '2025-04-01', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rocky', 4, 12, '2024-11-22', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Rosie', 1, 1, '2025-03-12', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lucy', 2, 8, '2025-03-10', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Toby', 4, 1, '2025-04-25', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Oscar', 3, 3, '2025-02-05', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Nala', 4, 6, '2025-01-19', FALSE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Simba', 2, 2, '2025-04-30', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Lily', 4, 2, '2025-02-12', TRUE);
INSERT INTO animals (name, species_id, age, arrived_on, adopted) VALUES ('Ziggy', 2, 8, '2024-11-23', FALSE);

INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (9, 'John Smith', '2025-03-11', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (10, 'Jane Doe', '2025-02-23', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (11, 'Jane Doe', '2025-05-23', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (21, 'Chris Johnson', '2025-06-04', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (25, 'Jane Doe', '2025-06-02', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (28, 'Chris Johnson', '2025-06-06', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (29, 'John Smith', '2024-12-25', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (31, 'Michael Brown', '2025-04-24', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (32, 'Chris Johnson', '2025-05-19', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (33, 'Jane Doe', '2025-05-19', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (34, 'Emily Davis', '2025-06-10', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (36, 'Michael Brown', '2025-05-16', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (39, 'John Smith', '2025-04-20', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (42, 'Michael Brown', '2025-03-09', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (45, 'John Smith', '2025-06-09', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (47, 'Jane Doe', '2025-06-07', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (48, 'Linda Wilson', '2025-04-30', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (49, 'Michael Brown', '2025-06-09', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (58, 'Linda Wilson', '2024-11-23', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (63, 'Michael Brown', '2025-05-20', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (64, 'Emily Davis', '2025-03-04', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (68, 'Michael Brown', '2025-01-05', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (81, 'Jane Doe', '2025-05-24', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (85, 'Emily Davis', '2025-05-25', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (86, 'Michael Brown', '2025-05-16', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (87, 'John Smith', '2025-05-26', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (89, 'Michael Brown', '2025-05-18', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (90, 'John Smith', '2025-04-01', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (93, 'Michael Brown', '2025-02-24', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (95, 'Chris Johnson', '2025-01-22', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (98, 'Chris Johnson', '2025-05-24', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (100, 'Michael Brown', '2025-04-29', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (102, 'Linda Wilson', '2025-03-03', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (103, 'Linda Wilson', '2025-04-19', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (104, 'Emily Davis', '2025-05-14', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (107, 'Linda Wilson', '2025-06-11', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (109, 'Jane Doe', '2025-03-21', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (112, 'Michael Brown', '2025-05-29', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (114, 'Michael Brown', '2025-05-14', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (117, 'John Smith', '2025-03-22', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (119, 'Michael Brown', '2025-01-14', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (120, 'John Smith', '2025-05-23', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (121, 'Chris Johnson', '2025-06-09', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (123, 'Linda Wilson', '2025-05-30', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (125, 'Chris Johnson', '2025-04-05', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (126, 'Jane Doe', '2024-12-29', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (130, 'Michael Brown', '2025-04-27', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (131, 'John Smith', '2025-04-21', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (137, 'Emily Davis', '2025-05-25', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (138, 'Michael Brown', '2025-03-01', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (140, 'Chris Johnson', '2025-05-05', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (142, 'Chris Johnson', '2025-03-03', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (146, 'John Smith', '2025-06-02', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (147, 'Linda Wilson', '2025-02-17', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (149, 'Linda Wilson', '2025-03-18', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (150, 'Michael Brown', '2025-06-04', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (152, 'Chris Johnson', '2025-02-18', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (155, 'John Smith', '2025-05-23', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (156, 'Chris Johnson', '2025-06-08', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (165, 'Jane Doe', '2025-04-07', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (167, 'John Smith', '2025-04-07', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (170, 'Michael Brown', '2025-03-02', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (171, 'Emily Davis', '2025-06-03', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (173, 'John Smith', '2025-06-05', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (177, 'Jane Doe', '2025-05-07', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (184, 'Jane Doe', '2025-05-20', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (195, 'John Smith', '2025-05-11', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (196, 'Emily Davis', '2025-01-10', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (197, 'Emily Davis', '2025-04-17', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (198, 'Linda Wilson', '2025-04-22', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (199, 'Jane Doe', '2025-02-28', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (203, 'Jane Doe', '2025-03-23', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (205, 'Emily Davis', '2025-04-23', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (206, 'Linda Wilson', '2025-03-17', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (208, 'Jane Doe', '2025-05-19', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (209, 'Linda Wilson', '2025-05-09', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (211, 'Michael Brown', '2025-05-10', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (218, 'John Smith', '2025-03-25', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (222, 'Emily Davis', '2025-05-16', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (226, 'Emily Davis', '2025-06-07', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (229, 'Michael Brown', '2025-05-28', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (230, 'John Smith', '2025-05-16', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (231, 'Chris Johnson', '2025-02-24', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (232, 'Emily Davis', '2025-04-02', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (233, 'Michael Brown', '2025-04-01', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (234, 'Chris Johnson', '2025-06-09', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (235, 'Chris Johnson', '2025-04-25', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (236, 'Jane Doe', '2025-02-23', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (237, 'Linda Wilson', '2025-06-07', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (238, 'Linda Wilson', '2025-05-27', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (239, 'Emily Davis', '2025-06-06', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (240, 'Michael Brown', '2025-05-17', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (243, 'Jane Doe', '2025-05-29', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (245, 'Chris Johnson', '2025-05-26', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (248, 'Linda Wilson', '2025-03-15', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (249, 'Jane Doe', '2025-05-18', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (254, 'Linda Wilson', '2025-02-24', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (255, 'Chris Johnson', '2025-05-28', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (256, 'Michael Brown', '2025-03-01', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (258, 'Jane Doe', '2025-04-04', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (259, 'John Smith', '2025-02-11', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (260, 'Michael Brown', '2025-05-03', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (264, 'Jane Doe', '2025-05-14', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (269, 'Linda Wilson', '2025-04-20', 5);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (271, 'Emily Davis', '2025-03-25', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (280, 'Jane Doe', '2025-06-08', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (283, 'Emily Davis', '2025-01-26', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (286, 'Michael Brown', '2025-04-16', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (288, 'Emily Davis', '2025-05-07', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (289, 'Chris Johnson', '2025-03-18', 2);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (290, 'Jane Doe', '2025-04-20', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (291, 'John Smith', '2025-04-04', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (292, 'Chris Johnson', '2025-01-02', 4);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (294, 'Emily Davis', '2025-04-11', 1);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (298, 'Michael Brown', '2025-05-04', 3);
INSERT INTO adoptions (animal_id, adopted_by, adopted_on, staff_id) VALUES (299, 'Chris Johnson', '2025-03-07', 1);


