version: "2"
linters:
  enable:
    - errchkjson
    - nilerr
    - protogetter
    - lll
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
  settings:
    lll:
      line-length: 150

formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
