# the timeout for all queries
queryTimeout = 60 

# the max number of rows to fetch when viewing table data (does not apply to ad-hoc queries)
tableDataRowLimit = 100

[connections]

[connections.animals_mysql]
driver           = "mysql"
host             = "localhost"
port             = 3306
user             = "qrypad"
insecurePassword = "qrypad"
database         = "qrypad"

[connections.animals_pg]
driver           = "postgres"
host             = "localhost"
port             = 50403
user             = "qrypad"
insecurePassword = "qrypad"
database         = "qrypad"

[theme]
# catppuccin-mocha (default) / kanagawa-wave / rose-pine-moon
name = "rose-pine-moon"
# borderActive          = { bg = "", fg = "#ff00ff" }
# currentStatement      = { bg = "", fg = "" }
# databaseSwitcherPopup = { bg = "", fg = "" }
# error                 = { bg = "", fg = "" }
# helpPopup             = { bg = "", fg = "" }
# helpKey               = { bg = "", fg = "" }
# helpDesc              = { bg = "", fg = "" }
# panelTitle            = { bg = "", fg = "" }
# panelTitleActive      = { bg = "", fg = "" }
# rowDetailsPopup       = { bg = "", fg = "" }
# spinner               = { bg = "", fg = "" }
# statusBar             = { bg = "", fg = "" }
# tableBorder           = { bg = "", fg = "" }
# tableHeader           = { bg = "", fg = "" }
# text                  = { bg = "", fg = "" }
# titleBar              = { bg = "", fg = "" }

[keys]
# CopyValue       = ""
# ExecuteQuery    = ""
# Help            = ""
# NextPanel       = ""
# NextTab         = ""
# OpenInEditor    = ""
# PrevPanel       = ""
# PrevTab         = ""
# ReloadQuery     = ""
# SaveQuery       = ""
# SwitchDatabase  = ""
# ToggleLeftPanel = ""
# UpdatePassword  = ""
# ViewData        = ""
# ViewDataDesc    = ""

