# the timeout for all queries
queryTimeout = 60 

# the max number of rows to fetch when viewing table data (does not apply to ad-hoc queries)
tableDataRowLimit = 100

[databases]

[databases.music]
driver = "mysql"
host = "localhost"
port = 3306
user = "root"
password = "123456"
database = "animals.0"

[databases.animals]
driver = "postgres"
host = "localhost"
port = 50403
user = "postgres"
password = "postgres"
database = "postgres"
