services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '50403:5432'
    volumes: 
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
