services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=qrypad
      - POSTGRES_PASSWORD=qrypad
      - POSTGRES_DB=qrypad
    ports:
      - "50403:5432"
    volumes:
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qrypad -d qrypad"]
      interval: 2s
      timeout: 5s
      retries: 30
      start_period: 5s
volumes:
  db:
    driver: local
